apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-world
spec:
  selector:
    matchLabels:
      app: postgres-world
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-world
    spec:
      containers:
        - image: docker.io/ghusta/postgres-world-db:2.10
          name: postgres-world
          ports:
            - containerPort: 5432
              name: postgres-world

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-world
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-world
  clusterIP: None
